package app.coronawarn.datadonation.services.ppac.android.controller;


public enum ApiErrorCode {

  APK_CERTIFICATE_MISMATCH,
  APK_PACKAGE_NAME_MISMATCH,
  ATTESTATION_EXPIRED,
  BASIC_INTEGRITY_REQUIRED,
  CTS_PROFILE_MATCH_REQUIRED,
  EVALUATION_TYPE_BASIC_REQUIRED,
  EVALUATION_TYPE_HARDWARE_BACKED_REQUIRED,
  JWS_SIGNATURE_VERIFICATION_FAILED,
  NONCE_MISMATCH,
  SALT_REDEEMED,
  
  /* Below are technical error codes */
  INTERNAL_SERVER_ERROR,
  UNKNOWN;
}
