---
spring:
  flyway:
    password: ${POSTGRESQL_PASSWORD_FLYWAY}
    user: ${POSTGRESQL_USER_FLYWAY}
    locations: classpath:/db/migration, classpath:/db/specific/{vendor}
    schemas: data_donation
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USER_SRS}
    password: ${POSTGRESQL_PASSWORD_SRS}
    hikari:
      schema: data_donation
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}?ssl=true&sslmode=verify-full&sslrootcert=${SSL_POSTGRES_CERTIFICATE_PATH}&sslcert=${SSL_SRS_CERTIFICATE_PATH}&sslkey=${SSL_SRS_PRIVATE_KEY_PATH}

