---

spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
  # Postgres configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8002/cwa
    username: postgres
    password: postgres

ppac:
  ppac-ios-jwt-key-id: ${$PPAC_IOS_JWT_KEY_ID:changeMe}
  ppac-ios-jwt-team-id: ${$PPAC_IOS_JWT_TEAM_ID:changMe}
  device-identification-url: ${APPLE_DEVICE_API_URL:https://api.development.devicecheck.apple.com}