CREATE SCHEMA IF NOT EXISTS data_donation;

-- create roles
CREATE ROLE cwa_ppdd_user
  NOLOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT CONNECT ON DATABASE cwa TO cwa_ppdd_user;
GRANT USAGE ON SCHEMA data_donation TO cwa_ppdd_user;

CREATE ROLE cwa_ppdd_flyway
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;

GRANT ALL ON SCHEMA data_donation TO cwa_ppdd_flyway;

CREATE ROLE cwa_ppdd_edus
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;

CREATE ROLE cwa_ppdd_ppac
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;
