CREATE SCHEMA IF NOT EXISTS data_donation;

-- create roles
CREATE ROLE cwa_ppdd_user
  NOLOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT CONNECT ON DATABASE cwa TO cwa_ppdd_user;
GRANT USAGE ON SCHEMA data_donation TO cwa_ppdd_user;

CREATE ROLE cwa_ppdd_flyway
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;

GRANT CREATE ON SCHEMA data_donation TO cwa_ppdd_flyway;

CREATE ROLE cwa_ppdd_edus
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;

CREATE ROLE cwa_ppdd_ppac
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  IN ROLE cwa_ppdd_user;

 GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA data_donation TO cwa_ppdd_ppac;
 GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA data_donation TO cwa_ppdd_edus;
 GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA data_donation TO cwa_ppdd_flyway;
 GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA data_donation TO cwa_ppdd_ppac;

